### ISSUE TITLE
add description and tags to the repository

### ISSUE THREAD

**Issue by AndreVarandas** [FranAmorim/tiink#33]
We should add a description and tags to the repository, for it to be easily discovered.

Description:
"TeaTime is a simple Job Schedule for NodeJS. Don't miss your tea!"

**Comment by Godje** [comment]
Tags could be `javascript`, `nodejs`, `scheduler`
Description of the repostiry could just be:
"Simple job schedule module for NodeJS"

**Comment by AndreVarandas** [comment]
@FranAmorim I think we should follow @Godje solution for this. Can you handle it?
